// Code generated by goyacc -o internals/parser.go internals/parser.y. DO NOT EDIT.

//line internals/parser.y:2
package internals

import __yyfmt__ "fmt"

//line internals/parser.y:2

var SymbolTable = []map[string]*IDNode{}
var Root Node
var current_symbol_index = -1

var predefinedIDs = []*IDNode{}
var inputDefs = [][]*IDNode{}
var outputDefs = [][]*IDNode{}
var globalDefs = []*GlobalDefNode{}

var GLOBAL bool = true

//line internals/parser.y:17
type yySymType struct {
	yys  int
	n    int
	name string
	tt   Typos
	*IDNode
	Node
}

const INPUT = 57346
const ID = 57347
const END = 57348
const OUTPUT = 57349
const ON = 57350
const ASSIGN = 57351
const COMMA = 57352
const NUM = 57353
const DO = 57354
const SEND = 57355
const LPAR = 57356
const RPAR = 57357
const PIPE = 57358
const LBR = 57359
const RBR = 57360
const BOOL = 57361
const INT = 57362
const EQ = 57363
const NEQ = 57364
const GE = 57365
const G = 57366
const LE = 57367
const L = 57368
const ADD = 57369
const MINUS = 57370
const DIV = 57371
const EXP = 57372
const TIMES = 57373
const AND = 57374
const OR = 57375
const NOT = 57376
const ITE = 57377
const SC = 57378
const DIESI = 57379
const AT = 57380
const FALSE = 57381
const TRUE = 57382
const INITIATE = 57383

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"INPUT",
	"ID",
	"END",
	"OUTPUT",
	"ON",
	"ASSIGN",
	"COMMA",
	"NUM",
	"DO",
	"SEND",
	"LPAR",
	"RPAR",
	"PIPE",
	"LBR",
	"RBR",
	"BOOL",
	"INT",
	"EQ",
	"NEQ",
	"GE",
	"G",
	"LE",
	"L",
	"ADD",
	"MINUS",
	"DIV",
	"EXP",
	"TIMES",
	"AND",
	"OR",
	"NOT",
	"ITE",
	"SC",
	"DIESI",
	"AT",
	"FALSE",
	"TRUE",
	"INITIATE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line internals/parser.y:443

//line yacctab:1
var yyExca = [...]int8{
	-1, 0,
	8, 6,
	-2, 1,
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 187

var yyAct = [...]uint8{
	90, 47, 57, 50, 99, 55, 54, 58, 61, 56,
	23, 3, 70, 126, 29, 53, 72, 27, 63, 36,
	81, 62, 87, 52, 88, 70, 123, 25, 79, 80,
	129, 63, 117, 134, 62, 64, 52, 132, 21, 22,
	43, 59, 51, 49, 67, 65, 68, 69, 64, 81,
	81, 125, 81, 83, 59, 41, 70, 67, 65, 68,
	69, 38, 63, 92, 119, 84, 91, 94, 95, 89,
	96, 86, 93, 85, 101, 102, 103, 104, 105, 106,
	100, 11, 12, 9, 28, 112, 110, 82, 109, 97,
	71, 113, 114, 70, 116, 107, 108, 115, 111, 63,
	120, 19, 84, 26, 52, 70, 118, 122, 40, 79,
	80, 63, 121, 31, 84, 30, 64, 26, 79, 80,
	49, 124, 15, 131, 49, 128, 65, 127, 64, 130,
	29, 100, 49, 133, 118, 11, 12, 42, 65, 17,
	78, 77, 75, 76, 73, 74, 79, 80, 78, 77,
	75, 76, 73, 74, 79, 80, 70, 6, 8, 33,
	44, 70, 63, 45, 37, 84, 16, 18, 14, 5,
	10, 20, 7, 2, 13, 98, 39, 60, 66, 34,
	32, 24, 1, 4, 35, 46, 48,
}

var yyPact = [...]int16{
	-30, -1000, 149, 62, 149, -1000, 163, 116, -1000, 130,
	162, -1000, -1000, -1000, 87, -1000, -1000, -1, -1000, 62,
	-19, -1000, -1000, -1000, 69, 120, -1000, -1000, 103, 62,
	152, -1000, 159, 62, 95, 159, -1000, 128, 4, 154,
	158, -1000, 7, -1000, -1000, 76, -20, -1000, -1000, 127,
	-13, 73, 88, 42, -10, -1000, -1000, -6, -1000, 20,
	-1000, -1000, 20, -1000, 100, 151, -1000, 51, -1000, -1000,
	-1000, 156, -1000, 88, 88, 88, 88, 88, 88, 100,
	100, 20, 20, 82, 88, 100, 100, 20, 100, -1000,
	127, 17, 119, -1000, -1000, 47, -1000, 151, 97, -1000,
	-1000, 1, 1, 1, 1, 1, 1, 42, 42, -10,
	16, -1000, 91, -1000, -1000, -1000, -1000, -1000, -1000, 20,
	34, -23, 156, 20, 12, 20, -1000, -1000, 113, -1000,
	19, 20, -1000, 18, -1000,
}

var yyPgo = [...]uint8{
	0, 8, 186, 185, 184, 183, 169, 83, 27, 182,
	181, 180, 179, 19, 0, 1, 15, 5, 7, 2,
	178, 3, 6, 9, 177, 176, 175, 4, 173, 172,
	158, 171, 170,
}

var yyR1 = [...]int8{
	0, 9, 9, 5, 5, 28, 28, 29, 29, 30,
	31, 31, 31, 6, 10, 11, 12, 4, 4, 13,
	25, 26, 26, 27, 3, 3, 15, 15, 21, 21,
	22, 22, 23, 23, 24, 24, 24, 24, 24, 24,
	20, 20, 20, 20, 20, 20, 14, 14, 14, 14,
	16, 16, 16, 17, 17, 18, 18, 18, 2, 8,
	8, 1, 19, 19, 19, 7, 32, 32,
}

var yyR2 = [...]int8{
	0, 0, 2, 2, 1, 3, 0, 2, 1, 4,
	1, 1, 1, 10, 1, 3, 1, 2, 1, 4,
	6, 3, 1, 1, 1, 1, 1, 1, 3, 1,
	3, 1, 2, 1, 1, 3, 2, 6, 1, 1,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
	3, 3, 1, 3, 1, 2, 5, 1, 8, 3,
	1, 1, 1, 3, 1, 2, 1, 1,
}

var yyChk = [...]int16{
	-1000, -9, -28, 41, -5, -6, 8, -29, -30, -7,
	-32, 19, 20, -6, 5, 6, -30, 9, 5, 14,
	-31, 39, 40, 11, -10, -8, -7, 36, 15, 10,
	12, -7, -11, 7, -12, -4, -13, 5, -8, -25,
	13, -13, 9, 36, 6, 5, -3, -15, -2, -14,
	-21, 35, 16, -16, -22, -17, -23, -19, -18, 34,
	-24, -1, 14, 11, 28, 38, -20, 37, 39, 40,
	5, 14, 36, 25, 26, 23, 24, 22, 21, 27,
	28, 33, 14, -14, 14, 31, 29, 32, 30, -23,
	-14, -21, -14, -18, -19, -19, -19, 38, -26, -27,
	-1, -14, -14, -14, -14, -14, -14, -16, -16, -22,
	-21, 16, -14, -17, -17, -23, -17, 15, 15, 17,
	-19, 15, 10, 10, -15, 17, 36, -27, -15, 18,
	-21, 10, 18, -15, 15,
}

var yyDef = [...]int8{
	-2, -2, 0, 0, 2, 4, 0, 0, 8, 0,
	0, 66, 67, 3, 0, 5, 7, 0, 65, 0,
	0, 10, 11, 12, 0, 14, 60, 9, 0, 0,
	0, 59, 0, 0, 0, 16, 18, 0, 0, 0,
	0, 17, 0, 15, 13, 0, 0, 24, 25, 26,
	27, 0, 0, 49, 29, 52, 31, 57, 54, 0,
	33, 62, 0, 64, 0, 0, 34, 0, 38, 39,
	61, 0, 19, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 32,
	0, 0, 0, 55, 57, 0, 36, 0, 0, 22,
	23, 40, 41, 42, 43, 44, 45, 46, 47, 28,
	0, 48, 0, 50, 51, 30, 53, 35, 63, 0,
	0, 0, 0, 0, 0, 0, 20, 21, 0, 56,
	0, 0, 37, 0, 58,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internals/parser.y:34
		{

			yyVAL.Node = EmptyProgramNode{}
			Root = yyVAL.Node
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internals/parser.y:39
		{

			yyVAL.Node = ProgramNode{
				GlobalVars: yyDollar[1].Node,
				Events:     yyDollar[2].Node,
			}
			Root = yyVAL.Node
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internals/parser.y:49
		{
			yyVAL.Node = EventListNode{yyDollar[1].Node, yyDollar[2].Node}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:52
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:57
		{

			createSymbolTable()
			GLOBAL = false

			yyVAL.Node = yyDollar[2].Node
		}
	case 6:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internals/parser.y:64
		{

			createSymbolTable()
			GLOBAL = false

			yyVAL.Node = EmptyGlobalDefNode{}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internals/parser.y:73
		{

			yyVAL.Node = GlobalDefListNode{
				GlobalDefinitions: yyDollar[1].Node,
				GlobalDefinition:  yyDollar[2].Node,
			}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:80
		{

			yyVAL.Node = yyDollar[1].Node
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internals/parser.y:86
		{

			assertSameTypeNodes(yyDollar[1].Node.(VarDeclNode).IDVar, yyDollar[3].Node)

			p := GlobalDefNode{
				VarDecl: yyDollar[1].Node,
				Value:   yyDollar[3].Node,
			}

			globalDefs = append(globalDefs, &p)

			yyVAL.Node = p
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:101
		{
			yyVAL.Node = BooleanNode{"False"}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:104
		{
			yyVAL.Node = BooleanNode{"True"}
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:107
		{
			yyVAL.Node = NumNode{yyDollar[1].n}
		}
	case 13:
		yyDollar = yyS[yypt-10 : yypt+1]
//line internals/parser.y:112
		{

			yyVAL.Node = EventNode{
				Name:       yyDollar[2].name,
				CurIndex:   current_symbol_index,
				InputsLen:  len(inputDefs[current_symbol_index-1]),
				OutputsLen: len(outputDefs[current_symbol_index-1]),
				Inputs:     yyDollar[4].Node,
				Outputs:    yyDollar[7].Node,
				Defs:       yyDollar[8].Node,
				SendStmt:   yyDollar[9].Node,
			}

			createSymbolTable()

		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:130
		{

			for _, idNode := range predefinedIDs {
				idNode.tstream = InputStream
			}

			copyOfDefs := make([]*IDNode, len(predefinedIDs))
			copy(copyOfDefs, predefinedIDs[:])
			inputDefs = append(inputDefs, copyOfDefs)

			predefinedIDs = predefinedIDs[:0]

			yyVAL.Node = InputNode{yyDollar[1].Node}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:147
		{

			for _, idNode := range predefinedIDs {
				idNode.tstream = OutputStream
			}

			copyOfDefs := make([]*IDNode, len(predefinedIDs))
			copy(copyOfDefs, predefinedIDs[:])
			outputDefs = append(outputDefs, copyOfDefs)

			predefinedIDs = predefinedIDs[:0]

			yyVAL.Node = OutputNode{yyDollar[2].Node}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:163
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internals/parser.y:168
		{

			yyVAL.Node = StatementListNode{
				Left:  yyDollar[1].Node,
				Right: yyDollar[2].Node,
			}

		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:176
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internals/parser.y:181
		{

			assertDefined(yyDollar[1].name)
			assertSameType(yyDollar[1].name, yyDollar[3].Node)

			if !(getSymbol(yyDollar[1].name).tstream == OutputStream) {
				compilerError("Variable " + yyDollar[1].name + " is not output stream.")
			}

			yyVAL.Node = StatementNode{
				Lval: getSymbol(yyDollar[1].name),
				Rval: yyDollar[3].Node,
			}

		}
	case 20:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internals/parser.y:198
		{
			yyVAL.Node = SendNode{
				Name:    yyDollar[2].name,
				OutVars: yyDollar[4].Node,
			}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:206
		{

			yyVAL.Node = OutVarListNode{
				OutVars: yyDollar[1].Node,
				OutVar:  yyDollar[3].Node,
			}
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:213
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:218
		{

			yyVAL.Node = OutVarNode{
				Var: yyDollar[1].Node,
			}

		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:228
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:231
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:236
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:239
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:244
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "or", yyDollar[3].Node, Boolean}
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:247
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:252
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "and", yyDollar[3].Node, Boolean}
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:255
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internals/parser.y:260
		{
			yyVAL.Node = UnaryOpNode{"not", yyDollar[2].Node, Boolean}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:263
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:268
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:271
		{
			yyVAL.Node = ParenthesisOpNode{yyDollar[2].Node, Boolean}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internals/parser.y:274
		{
			assertNodeType(yyDollar[2].Node, Boolean)
			yyVAL.Node = yyDollar[2].Node
		}
	case 37:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internals/parser.y:278
		{

			assertSameTypeNodes(yyDollar[3].Node, yyDollar[5].Node)
			yyVAL.Node = PastOpNode{yyDollar[3].Node, yyDollar[3].Node.(*IDNode).getType(), yyDollar[5].Node}

		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:284
		{
			yyVAL.Node = BooleanNode{"False"}
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:287
		{
			yyVAL.Node = BooleanNode{"True"}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:292
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "<=", yyDollar[3].Node, Boolean}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:295
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "<", yyDollar[3].Node, Boolean}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:298
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, ">=", yyDollar[3].Node, Boolean}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:301
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, ">", yyDollar[3].Node, Boolean}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:304
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "!=", yyDollar[3].Node, Boolean}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:307
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "==", yyDollar[3].Node, Boolean}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:316
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "+", yyDollar[3].Node, Integer}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:319
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "-", yyDollar[3].Node, Integer}
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:322
		{
			yyVAL.Node = AbsOpNode{yyDollar[2].Node, Integer}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:326
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:331
		{

			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "*", yyDollar[3].Node, Integer}

		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:336
		{

			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "//", yyDollar[3].Node, Integer}

		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:341
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:346
		{
			yyVAL.Node = BinaryOpNode{yyDollar[1].Node, "**", yyDollar[3].Node, Integer}
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:349
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internals/parser.y:354
		{
			yyVAL.Node = UnaryOpNode{"-", yyDollar[2].Node, Integer}
		}
	case 56:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internals/parser.y:357
		{

			assertSameTypeNodes(yyDollar[2].Node, yyDollar[4].Node)
			yyVAL.Node = PastOpNode{yyDollar[2].Node, yyDollar[2].Node.(*IDNode).getType(), yyDollar[4].Node}

		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:363
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 58:
		yyDollar = yyS[yypt-8 : yypt+1]
//line internals/parser.y:368
		{

			assertSameTypeNodes(yyDollar[5].Node, yyDollar[7].Node)

			yyVAL.Node = IteNode{
				Condition: yyDollar[3].Node,
				Then:      yyDollar[5].Node,
				Else:      yyDollar[7].Node,
				Type:      getExpressionType(yyDollar[5].Node),
			}
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:382
		{
			yyVAL.Node = VarDecListNode{yyDollar[1].Node, yyDollar[3].Node}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:385
		{

			yyVAL.Node = yyDollar[1].Node
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:391
		{
			assertDefined(yyDollar[1].name)
			yyVAL.Node = getSymbol(yyDollar[1].name)
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:397
		{
			yyVAL.Node = yyDollar[1].Node
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internals/parser.y:400
		{
			yyVAL.Node = ParenthesisOpNode{yyDollar[2].Node, Integer}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:403
		{
			yyVAL.Node = NumNode{yyDollar[1].n}
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internals/parser.y:408
		{

			if definedSymbol(yyDollar[2].name) {
				compilerError("Syntax Error: The variable already exists.")
			}

			pr := prefix()
			p := IDNode{prefix: pr, name: yyDollar[2].name, Type: yyDollar[1].tt}

			if GLOBAL == false {

				predefinedIDs = append(predefinedIDs, &p)
			}

			n := VarDeclNode{
				Type:  yyDollar[1].tt,
				IDVar: &p,
				Value: nil,
			}

			addSymbol(yyDollar[2].name, &p)

			yyVAL.Node = n
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:433
		{
			var t Typos = Boolean
			yyVAL.tt = t
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internals/parser.y:437
		{
			var t Typos = Integer
			yyVAL.tt = t
		}
	}
	goto yystack /* stack new state and value */
}
